### ISSUE TITLE
issues in my laptop windows 11

### ISSUE THREAD

**Issue by ayanmondal1** [twxs/vs.language.cmake#125]
Running] cd "c:\Users\Ayan\OneDrive\Desktop\ayan\" && gcc ayanmondal.c -o ayanmondal && "c:\Users\Ayan\OneDrive\Desktop\ayan\"ayanmondal
gcc: error: ayanmondal.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

**Comment by ayanmondal1** [comment]
![Screenshot 2024-04-04 230047](https://github.com/twxs/vs.language.cmake/assets/166053235/975457fd-e90c-4bc0-b8e2-349c0ecc022d)

**Comment by twxs** [comment]
Hello,
I think it is not related to this CMake extension. 
It seems that the file is mark as not saved in the editor....
