### ISSUE TITLE
Syntax highlighting not working properly when escaping quotes

### ISSUE THREAD

**Issue by jsgaonac** [twxs/vs.language.cmake#14]
I have the following in my common.cmake:
```
COMMAND copy \"$(TargetPath)\" .\\dist\\bin )
endif(WIN32 AND NOT MINGW)
```
The characters following the first escaped quote are interpreted as a string, so the 'endif' and other directives are not highlighted with the right color.

**Comment by twxs** [comment]
Hi, 
thank you for this report, I will patch the tmLanguage file to support it.

**Comment by twxs** [comment]
@jsgaonac you could try the next update [here]( https://github.com/twxs/vs.language.cmake/releases/tag/v0.0.16-beta1)

**Comment by jsgaonac** [comment]
It works perfect now. Thanks.
