### ISSUE TITLE
Outlining for cmake scripts

### ISSUE THREAD

**Issue by amigo421** [twxs/vs.language.cmake#26]
could you add (if this feature is possbile to be implemented in the extension)
 - the popup with a functions outlining (like it's done for e.g. JS, C++, Python - Ctrl+Shift+O)
 - navigation throu the files via Ctrl+Click from function using to function declaration

Thank you!

**Comment by twxs** [comment]
I have a work in progress prototype, that provide these features.

https://twitter.com/twxs/status/737887620441772037

I will release it as soon as all issues will be fixed

**Comment by amigo421** [comment]
reviewed the animation. thank you!
then please close the request
