### ISSUE TITLE
Support for cmake_format

### ISSUE THREAD

**Issue by Stanzilla** [twxs/vs.language.cmake#35]
Hey there, any plans to add support for https://github.com/cheshirekow/cmake_format?

**Comment by mariusz102102** [comment]
+1 Please add formatting for cmake.

**Comment by twxs** [comment]
I will take a look at cmake_format. I just need to find some time slice...

**Comment by tobse80** [comment]
Sounds very useful if formatting of cmake files is supported by this project. Thumbs up!
