### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by ajssousa** [twxs/vs.language.cmake#36]
Hi.

It would be good to add support to WSL in the cmake extension.

Thanks.

**Comment by Luberen** [comment]
I definitely need this feature. I installed CMake on Ubuntu WSL but the plugin doesn't recognize it.

**Comment by g-berthiaume** [comment]
+1 for the WSL support.

I tried to change the cmake path, but it didn't worked.
`"cmake.cmakePath": "/usr/bin/cmake"`

**Comment by twxs** [comment]
```
"cmake.cmakePath": "wsl.exe /usr/bin/cmake"
```

is working

**Comment by Gussy** [comment]
> ```
> "cmake.cmakePath": "wsl.exe /usr/bin/cmake"
> ```
> 
> is working

This doesn't seem to work, at least on the extension v0.0.17, and VS Code v1.44.2.
