### ISSUE TITLE
No CMake found on $PATH

### ISSUE THREAD

**Issue by elileka** [twxs/vs.language.cmake#38]
Hello,

I have recently installed Visual Studio Code for Windows (Windows 10). After the installation of the cmake plugin, it seems to be missing from the path:
CMake build ---> "No CMake found on $PATH"
From the terminal:
cmake --version
cmake : The term 'cmake' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cmake --version
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (cmake:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Any idea how to solve this?

Thank you!

**Comment by twxs** [comment]
Hello, 

The CMake installer should add the installation folder in the PATH.
You can either add it to the PATH or in vscode settings define the full path of the CMake executable.
