### ISSUE TITLE
Impossible: CMake driver died immediately after successful configure

### ISSUE THREAD

**Issue by DavidBoelee** [twxs/vs.language.cmake#43]
Working in Windows 8, with Visual Studio Code I try to work with the files in this repo: [https://github.com/Lora-net/LoRaMac-node](url). Followed exactly the description that I found here: [https://github.com/Lora-net/LoRaMac-node/blob/develop/Doc/development-environment.md](url). I am usig MinGW.

But each time I want to build, I get these errors:

`Impossible: CMake driver died immediately after successful configure`
and
`Bad CMake executable "C:\CMake\bin". Is it installed or settings contain the correct path (cmake.cmakePath)?`

But C:\Make\bin is definatley in the system path, I doublechecked that by typing make in both a cmd window and in the terminal. As suggested elsewhere, I added:

```
    "cmake.cmakePath": "C:\\CMake\\bin",

  "cmake.preferredGenerators": [
    "MinGW Makefiles",
    "Ninja",
    "Unix Makefiles"
  ]
```

And in the kit file, I added:

`    "preferredGenerator": {
      "name": "MinGW Makefiles"`

But none of these solutions seem to work and now I am running out of options. Any help would be greatly appreciated!

**Comment by twxs** [comment]
Hi,
I think this issue is for the [vscode-cmake-tools]( https://github.com/twxs/vscode-cmake-tools) plugin
