### ISSUE TITLE
Case-Sensitivity Problem with CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by matthewdhunt** [twxs/vs.language.cmake#44]
Issue Type: <b>Bug</b>

I wanted to experiment with Visual Studio Code CMake support, so I took a project that we are currently building with Visual Studio 2017 + CMake and also with CMake 3.12 directly on different platforms.  I encountered a strange problem limited specifically to the Visual Studio Code integration.

In some of our projects, we check to see if the current source directory is the same as the project directory as follows:

`if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)`

I noticed this check was always failing, so I added some debug message statements.  For some strange reason, the drive letter in the CMAKE_SOURCE_DIR is always lowercase, and the PROJECT_SOURCE_DIR is upper case, e.g.

CMAKE_SOURCE_DIR = c:\Projects\...
PROJECT_SOURCE_DIR = C:\Projects\...

So, the comparison fails.  I checked running cmake on the Windows command line, and this isn't a problem, nor through the CMake GUI or the Visual Studio 2017 built-in CMake support.  This only happens with Visual Studio Code.

Extension version: 0.0.17
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by twxs** [comment]
Hi, this extension only provide completion and syntax highlighting, may be your issue is related to the [vscode-cmake-tools](https://github.com/vector-of-bool/vscode-cmake-tools) plugin.
