### ISSUE TITLE
CMake Debug No active kit

### ISSUE THREAD

**Issue by kinglionsz** [twxs/vs.language.cmake#51]
Issue Type: <b>Bug</b>

at wsl terminal ,cmake work ok.
but in the vs code windows,cmake build will report:
mpossible: CMake driver died immediately after successful configure

Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json or your Kit configuration.

source: cmake tools(extension)

Extension version: 0.0.17
VS Code version: Code - Insiders 1.36.0-insider (68a7e5bc437b38d0281df0756997a25da2a2900c, 2019-06-18T18:40:22.519Z)
OS version: Windows_NT x64 10.0.18917

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 2128)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.58GB free)|
|Process Argv|C:\Users\lyl\helloworld\src|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by twxs** [comment]
Hi,
I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

**Comment by kinglionsz** [comment]
now i download the camke msi file and install,it works ok.

**Comment by kinglionsz** [comment]
> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

thanks.

**Comment by kinglionsz** [comment]
> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

now i download the camke msi file and install,it works ok.
Originally posted by @kinglionsz in #51 (comment)
but there's issues.while cmake configure,cmake reports:
[cmake] The C compiler identification is unknown
[cmake] The CXX compiler identification is unknown
[cmake] Check for working C compiler: C:/Users/lyl/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/cc
[cmake] CMake Error: Generator: execution of make failed. Make command was: "C:/Users/lyl/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/make" "cmTC_b6cba/fast"
[cmake] Check for working C compiler: C:/Users/lyl/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/cc -- broken
[cmake] CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake] The C compiler
[cmake]
[cmake] "C:/Users/lyl/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/cc"
[cmake]
[cmake] is not able to compile a simple test program.
[cmake]
[cmake] It fails with the following output:
[cmake]
[cmake] Change Dir: c:/Users/lyl/helloworld/src/build/CMakeFiles/CMakeTmp
[cmake]
[cmake] Run Build Command:"C:/Users/lyl/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/make" "cmTC_b6cba/fast"
[cmake] %1 不是有效的 Win32 应用程序。
[cmake] Generator: execution of make failed. Make command was: "C:/Users/lyl/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/usr/bin/make" "cmTC_b6cba/fast"
[cmake]
[cmake]
[cmake]
[cmake]
[cmake] CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake] CMakeLists.txt:2 (project)
[cmake]
[cmake]
[cmake] Configuring incomplete, errors occurred!
the same CMakeLists.txt,at WSL terminal camke will be ok,build and debug no problem.

**Comment by kinglionsz** [comment]
> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi, Nicolas twxs:



> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi,

> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi,Nicolas 👍I have  installed the Remote Development extension pack(vs code version 1.36.0),and use Remote-WSL,then CMake tools works very good.
build & debug, no any problems.

tks. very much.
