### ISSUE TITLE
auto completion not working

### ISSUE THREAD

**Issue by brukted** [twxs/vs.language.cmake#66]
Auto completion is not working as intended it only suggests variables and commands that are already used in the file.
OS : Windows 10 home x64
CMake : 3.17.3
vs code: 1.46.0 (system setup)
Extension version: 0.0.17
CMake Tools version : 1.4.1

**Comment by Laefy** [comment]
I have the same issue.

OS : Windows 10 home x64
CMake : 3.16.2
VS Code: 1.52.1
CMake extension version: 0.0.17
CMake Tools extension version : 1.5.3

**Comment by brukted** [comment]
Seems like an abandoned project.
