### ISSUE TITLE
Online Help not Working

### ISSUE THREAD

**Issue by willyd** [twxs/vs.language.cmake#7]
Hi,

When I try to use the CMake Online Help I get the following error message:

No handler found for the command: 'cmake.onlineHelp'. An extension might be missing an activation event.

Should this work out-of-the-box or is there anything to configure?

**Comment by willyd** [comment]
It seems that this happens when the file opened when I typed the command was not a CMake file. After the command is invoked with a CMake file opened. Everyting works smoothly. However, when I press the Esc key to dissmiss the cmake online help the browser opens this page: https://cmake.org/cmake/help/latest/command/.html

**Comment by twxs** [comment]
Hi, 

Thank you for this report, I have fixed it and deployed the extension. 

You should be able update the extension in vscode : `F1` `>Extensions: Show Outdated Extensions`
